#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  local repo="$1"; shift
  http -b "https://api.github.com/repos/${repo}/releases"
}

source sub "$BASH_SOURCE" "$@"
