#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  if [[ "$#" == 0 ]]; then
    local repo="$(cd "./$(git rev-parse --show-cdup)" && cat .repo-name)"
  else
    local repo="$1"; shift
  fi

  repo="$(echo "$repo" | cut -d/ -f1-2)"

  {
    http -Ib "https://api.github.com/repos/${repo}/releases" | jq '.[]'
    http -Ib "https://api.github.com/repos/${repo}/tags" | jq '.[]'
  } | jq -s 'reduce .[] as $elems ([]; . + [$elems])'
}

source sub "$BASH_SOURCE" "$@"
