#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  local prefix="$(echo "$1" | cut -d/ -f3-)"
  gh releases "$@" | jq --arg prefix "$prefix" '
    map(select(.prerelease != true)) 
    | map({tag: (.tag_name//.name | gsub("^v";"")), assets: (.assets//[] | map(.browser_download_url))}) 
    | map(select(.tag | startswith($prefix))) 
    | .[0]'
}

source sub "$BASH_SOURCE" "$@"
