#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  if [[ "$#" == 0 ]]; then
    local repo="$(cd "./$(git rev-parse --show-cdup)" && cat .repo-name)"
  else
    local repo="$1"; shift
  fi
  http -b "https://api.github.com/repos/${repo}/releases"
}

source sub "$BASH_SOURCE" "$@"
