#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local url_hub

  case "${DISTRIB_ID}" in
    Darwin) url_hub="https://github.com/github/hub/releases/download/v${HUB_VERSION}/hub-darwin-amd64-${HUB_VERSION}.tgz" ;;
    *)      url_hub="https://github.com/github/hub/releases/download/v${HUB_VERSION}/hub-linux-amd64-${HUB_VERSION}.tgz" ;;
  esac

  local tmp_hub="$(mktemp -t XXXXXX)"
  trap "$(printf "rm -f '%q'" "$tmp_hub")" EXIT
  curl -sS -L -o "$tmp_hub" "$url_hub"
  chmod 755 "$tmp_hub"
  mkdir -p "$shome/vendor"
  mv -f "$tmp_hub" "$shome/vendor/hub-${HUB_VERSION}.tgz"
  (cd "$shome/vendor" && tar xfz "hub-${HUB_VERSION}.tgz")
  (set +f; cd "$shome/bin" && ln -nfs ../vendor/*${HUB_VERSION}*/bin/hub .)

  export GOPATH="$shome"
  go get -u github.com/aktau/github-release

  git clone git@github.com:whiteinge/ok.sh "$shome/vendor/ok.sh" || true
  cd "$shome/vendor/ok.sh"
  git pull
  ln -nfs "../vendor/ok.sh/ok.sh" "$shome/bin/ok.sh"
}

bootstrap
