#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  app compile bundler
  ln -nfs ../vendor/bundle/bin/ghi bin/
}

bootstrap
