#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile bundler
  ln -nfs ../vendor/bundle/bin/ghi bin/

  local url_hub

  case "$(uname -s)" in
    Darwin) url_hub="https://github.com/github/hub/releases/download/v${HUB_VERSION}/hub-darwin-amd64-${HUB_VERSION}.tgz" ;;
    *)      url_hub="https://github.com/github/hub/releases/download/v${HUB_VERSION}/hub-linux-amd64-${HUB_VERSION}.tgz" ;;
  esac

  local tmp_hub="$(mktemp -t XXXXXX)"
  trap "$(printf "rm -f '%q'" "$tmp_hub")" EXIT
  curl -sS -L -o "$tmp_hub" "$url_hub"
  chmod 755 "$tmp_hub"
  mv -f "$tmp_hub" "$shome/vendor/hub-${HUB_VERSION}.tgz"
  (cd "$shome/vendor" && tar xfz "hub-${HUB_VERSION}.tgz")
  (set +f; cd "$shome/bin" && ln -nfs ../vendor/*${HUB_VERSION}*/bin/hub .)
}

bootstrap
