#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"

  if ! type -P ok.sh >/dev/null; then
    return 1
  fi

  if [[ "$($shome/script/version | jq -r '.hub')" != "$HUB_VERSION" ]]; then
    return 1
  fi

  if [[ "$($shome/script/version | jq -r '.ghi')" != "$GHI_VERSION" ]]; then
    return 1
  fi

  if [[ "$($shome/script/version | jq -r '.["github-release"]')" != "$GITHUB_RELEASE_VERSION" ]]; then
    return 1
  fi

  return 0
}

source sub "$BASH_SOURCE" "$@"
