#!/usr/bin/env bash

function _github_profile {
  local shome="${_github_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  HUB_VERSION="2.2.9"
  GHI_VERSION="1.2.0"
}

_github_profile
